#!/bin/bash

set -e -u -o pipefail -o errtrace

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

export root=$(dirname "${0}" | while read a; do cd "${a}" && pwd && break; done)
# shellcheck source=./common.sh
source "${root}/common.sh"

payload=$(mktemp "${TMPDIR}/bitbucket-pullrequest-resource-check.XXXXXX")
cat > "${payload}" <&0

bitbucket_type=$(jq -r '.source.bitbucket_type // "server"' < "${payload}")
base_url=$(jq -r '.source.base_url // ""' < "${payload}")
username=$(jq -r '.source.username // ""' < "${payload}")
password=$(jq -r '.source.password // ""' < "${payload}")
project=$(jq -r '.source.project // ""' < "${payload}")
repository=$(jq -r '.source.repository // ""' < "${payload}")
limit=$(jq -r '.source.limit // "100"' < "${payload}")
source_branch=$(jq -r '.source.branch // ""' < ${payload})

version_updated_at=$(jq -r '.version.updated_at // 0' < "${payload}")
version_commit=$(jq -r '.version.commit // ""' < ${payload})

if [ -z "${base_url:-}" ]; then
    echo "error: source.base_url can't be empty"
    exit 1
fi

if [ -z "${project:-}" ]; then
    echo "error: source.project can't be empty"
    exit 1
fi

if [ -z "${repository:-}" ]; then
    echo "error: source.repository can't be empty"
    exit 1
fi

# Bitbucket Cloud and (self-hosted) Server APIs are a bit different
if [ "${bitbucket_type}" == "server" ]; then
    if [[ -n "${source_branch}" ]]; then
        branch_param="&at=refs/heads/${source_branch}"
    else
        branch_param=""
    fi
    uri="${base_url}/rest/api/1.0/projects/${project}/repos/${repository}/pull-requests?limit=${limit}&state=open${branch_param}"

    curl -s --fail -u "${username}:${password}" "${uri}" | jq -r \
        | jq -r --arg version_updated_at "${version_updated_at}" --arg version_commit $version_commit \
        '.values
        | map({
            id: .id | tostring,
            branch: .fromRef.id | tostring | (capture("refs/heads/(?<branch>.+)").branch // .),
            commit: .fromRef.latestCommit,
            updated_at: .updatedDate | tostring
        })
        | map(select(.commit != $version_commit))
        | map(select(.updated_at >= "${version_updated_at}"))
        | sort_by(.updated_at)' >&3
elif [ "${bitbucket_type}" == "cloud" ]; then
    uri="${base_url}/api/2.0/repositories/${project}/${repository}/pullrequests?limit=${limit}&state=OPEN"

    # write response to file as feeding it to jq from a variable doesnt work properly: JSON loses linefeed format in variable
    response=$(mktemp "${TMPDIR}/bitbucket-pullrequest-resource-check.XXXXXX")
    curl -s --fail -u "${username}:${password}" "${uri}" | jq -r '.values' > "${response}"
    prs="[]"
    while read -r pullrequest; do
        branch=$(echo "${pullrequest}" | jq -r '.source.branch.name')
        destination_branch=$(echo "${pullrequest}" | jq -r '.destination.branch.name')
        if [[ "${source_branch}" ]]; then
            [[ "${destination_branch}" == "${source_branch}" ]] || continue
        fi
        id=$(echo "${pullrequest}" | jq -r '.id')
        commit=$(echo "${pullrequest}" | jq -r '.source.commit.hash')
        date=$(echo "${pullrequest}" | jq -r '.updated_on')
        ## if [[ "${version_commit}" ]]; then
        ##     if [[ "${commit}" == "${version_commit}" ]]; then
        ##        continue
        ##     fi
        ## fi
        ## commit_url=$(echo "${pullrequest}" | jq -r '.source.commit.links.self.href')
        # replace the stupid /!api with /api
        ## commit_url=${commit_url//!api/api}

        ## commit_data=$(curl -s --fail -u "${username}:${password}" "${commit_url}")
        # get the commit date, which is when the PR last got updated code-wise.
        # the updated_on field in the PR also changes when comment added etc
        ##date=$(echo "$commit_data" | jq -r '.date')

        prs+="+ [{id:\"${id}\", branch: \"${branch}\", commit:\"${commit}\", updated_at:\"${date}\"}]"
    done < <(jq -c '.[]' "${response}")

    if [ "${prs}" == "[]" ]; then
        jq -n "$prs" >&3
        exit 0
    fi

    # take the list of PRs | sort by update-date of commits | remove the date | pick latest PR, wrap as array for concourse
    jq -n "$prs | sort_by(.updated_at) | map(del(.updated_at))" >&3
fi
